---
###############################################################################
# Import ZFS pools if defined
###############################################################################
#
# Args:
#   pool: dict - ZFS pool settings to import (from zfs_srv_pools).

- name: 'Import ZFS pool | cmd | query pool state'
  ansible.builtin.shell: >
    set -o pipefail &&
    /usr/sbin/zpool list -H | grep "{{ pool.name }}"
  args:
    executable: '/bin/bash'
  register: zfs__query
  changed_when: false
  failed_when: zfs__query.rc > 1

- name: 'Import ZFS pool | cmd | import {{ pool.name }}'
  when: zfs__query.rc == 1
  ansible.builtin.shell: >
     /usr/sbin/zpool import
     "{{ pool.name }}"
     {{ "-f" if zfs_flg_force_pools else "" }}
  args:
    executable: '/bin/bash'
  register: zfs__import
  changed_when: zfs__import.rc == 0

- name: '{{  "Import ZFS pool | systemd | enable scrubbing on " ~ pool.name }}'
  when: pool.scrub | lower != ''
  ansible.builtin.systemd:
    name:
      '{{ "zfs-scrub-" ~ pool.scrub | lower ~ "@" ~ pool.name ~ ".timer" }}'
    enabled: true
    state: 'started'

- name: '{{ "Import ZFS pool | systemd | disable scrubbing on " ~ pool.name }}'
  when: pool.scrub | lower == ''
  ansible.builtin.systemd:
    name: '{{ "zfs-scrub-" ~ item ~ "@" ~ pool.name ~ ".timer" }}'
    enabled: false
    state: 'stopped'
  loop:
    - 'monthly'
    - 'weekly'

- name: 'Import ZFS pool | set dataset options'
  when: pool.datasets | length > 0
  ansible.builtin.include_tasks: 'dataset.yml'
  vars:
    container: '{{ pool.name }}'
  loop: '{{ pool.datasets }}'
  loop_control:
    loop_var: 'set'
    label: '{{ set.name }}'
