---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'
- name: 'Import'
  ansible.builtin.import_tasks: 'import.yml'
- name: 'Snapshots'
  ansible.builtin.import_tasks: 'snapshots.yml'

- name: 'Restart ZFS shares'
  when: zfs_flg_pools_share_restart
  ansible.builtin.systemd:
    name: 'zfs-share'
    state: 'restarted'
