---
###############################################################################
# Default
###############################################################################
# ZFS module installs (non-secure boot), role account is created, snapshot
# script deployed and scheduled job is started. VM required as ZFS loads kernel
# modules.
#
# Tests:
# * zpool atime disabled.
# * zpool xattr is sa.
# * zpool dnode size is auto.
# * zpool NFS share is 'rw=10.10.10.0/24,sec=sys,mountpoint'.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'root'
    options:
      append_platform_to_hostname: false
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        zfs_create_user: true
        zfs_pools_restart_share_enable: true
platforms:
  - name: 'zfs-debian-12-vm-dataset'
    box: 'debian/bookworm64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: private_network  # network_name required
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # dataset options are always executed.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
