---
###############################################################################
# Default
###############################################################################
# ZFS module installs (non-secure boot), role account is created, snapshot
# script deployed and scheduled job is started. VM required as ZFS loads kernel
# modules.
#
# Advise using --destroy=never:
# This test is very heavy as file-based block devices are created on the VM to
# simulate physical disks for verifying ZFS commands.
#
# Tests:
# * zpool atime disabled.
# * zpool xattr is sa.
# * zpool dnode size is auto.
# * zpool NFS share is 'rw=10.10.10.0/24,sec=sys,mountpoint'.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        apt_srv_auto_grub_boot: true  # Testing VM only.
        zfs_create_user: true
        zfs_flg_snapshot: true
        zfs_cfg_snapshot_remote_user: 'zfs_snapshot'
        zfs_cfg_snapshot_remote_pool: 'test_pool'
        zfs_cfg_snapshot_remote_server: 'example.com'
        zfs_cfg_snapshot_remote_ssh_options:
          - '-i /root/backup/backup.key'
        zfs_flg_pools_share_restart: true
platforms:
  - name: 'zfs-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
