---
- name: 'Verify'
  hosts: 'all'
  gather_facts: true  # ansible_facts.mounts
  become: true
  tasks:
    - name: 'Verify | query default ZFS user creation'
      ansible.builtin.copy:
        content: "zfs_snapshot ALL=(ALL)NOPASSWD: /usr/sbin/zfs\n"
        dest: '/etc/sudoers.d/zfs_snapshot'
        owner: 'root'
        group: 'root'
        mode: '0440'
      check_mode: true
      diff: true
      register: _test_zfs_user

    - name: 'Verify | assert default ZFS user correct'
      ansible.builtin.assert:
        quiet: true
        that:
          - not _test_zfs_user.changed
        fail_msg: |
          ✘ zfs_user should have been created with sudoers access.

          Expected:
            /etc/sudoers.d/zfs_snapshot:
              zfs_snapshot ALL=(ALL)NOPASSWD: /usr/sbin/zfs

          Received:
            {{ _test_zfs_user.diff }}

    - name: 'Verify | /etc/zfs_snapshot/zfs_incremental_snapshot'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name:
          'Verify | /etc/zfs_snapshot/zfs_incremental_snapshot'
        test_src: 'files/zfs_incremental_snapshot'
        test_file: '/etc/zfs_snapshot/zfs_incremental_snapshot'
        test_owner: 'zfs_snapshot'
        test_group: 'zfs_snapshot'
        test_mode: '0755'
        test_diff: true

    - name: 'Verify | query ZFS pool test imported'
      ansible.builtin.command: 'zpool list test'
      register: _test_zfs_pool_test
      changed_when: false
      failed_when: false

    # Query mounts, not setting them.
    - name: 'Verify | query ZFS pool test mounted'
      ansible.builtin.command: 'mount'  # noqa: command-instead-of-module
      register: _test_zfs_pool_mount
      changed_when: false
      failed_when: false

    - name: 'Verify | assert ZFS pool test imported'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_zfs_pool_test.rc == 0
        fail_msg: >
          ✘ zpool test not imported. (exit code: {{ _test_zfs_pool_test.rc }}).

    - name: 'Verify | assert ZFS pool test mounted'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"test on /test" in _test_zfs_pool_mount.stdout'
        fail_msg: >
          ✘ zpool test should be mounted to /test.

    # systemd ansible module does not report timers.
    - name: 'Verify | gather timer status'  # noqa: command-instead-of-module
      ansible.builtin.command: 'systemctl list-timers'
      register: _test_zfs_scrub
      changed_when: false

    - name: 'Verify | assert scrub service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"zfs-scrub-monthly@test.timer" in _test_zfs_scrub.stdout'
        fail_msg: |
          ✘ zfs-scrub-monthy@test.timer should be in enabled list of timers.

          {{ _test_zfs_scrub.stdout }}
